name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn clean package
      - name: Build Docker image
        run: |
          docker build -t my-app .
          docker tag my-app mycontainermevlut.azurecr.io/my-app:latest
          docker push mycontainermevlut.azurecr.io/my-app:latest
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
