name: My First Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Perform build steps here

      - name: Trigger second workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MY_ACCESS_TOKEN }}
          repository: kaymazmevlut/apiforazure
          event-type: my-event
          client-payload: '{"foo": "bar"}'
